<?php

/**Autocomplete module
Author: Hávar Sigurðarson
TOVH
Description: module fyrir Drupal sem er textfield þar sem þú getur leitað eftir boardgames á 
BoardGameGeeks. Textfieldið autocompletar svo með því að sækja það sem matchar í BGG Apann.
*/

#--------------FORM------------------

#MENU
function form_autocomplete_menu() {
	$items = array();

	$items['modules/autocomplete'] = array(
		'title' => 'Boardgame Search',
		'description' => 'A form for autocompleting Board game searches',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('form_autocomplete_form'),
		'access callback' => TRUE,
		'autocomplete_path' => 'boardgamegeeks/autocomplete',
		'access_arguments' => array('use autocomplete'),
		'type' => MENU_CALLBACK
	);
	return $items;
}


function form_autocomplete_form($form, &$form_state) {
	$form['search'] = array(							#search text fieldið
		'#type' => 'textfield',
		'#size' => 30,
		'#maxlength' => 60,
		'#autocomplete_path' => 'user/autocomplete' 	#breyta þessu svo í custom autocomplete-ið til að overwrita default autocompletið
	);

	#$form['submit button'] = array(						#test button
	#	'#type' => 'submit',
	#	'#value' => t('Click here!'),
	#);

	return $form;
}

#VALIDATE
function form_autocomplete_form_validate($form, &$form_state) {

}
#SUBMIT
function form_autocomplete_form_submit($form, &$form_state) {
	
}


#--------------AUTO COMPLETE HANDLER------------------


#send string to this function and it queries BGG API and returns XML list of the resulting games
#if none are found returns nothing.
#uses CURL php-curl is required.


/** Opens a cURL connection to BGG API and searches for the string we provide. Returns the result to the handler

 * @param $string string 
 * 	String to search for
 * @return array 
 * 	Returns an array of the objects that match from BGG API
*/

function searchBGGbytext($string) {
	#$req = & new HTTP_Request("http://boardgamegeek.com/xmlapi/search?search=" . $string) #queries BGG API with our search string
	$cURL = curl_init();
	$setopt_array = array(CURLOPT_URL => "http://boardgamegeek.com/xmlapi/search?search=" . $string);
	curl_setopt_array($cURL, $setopt_array);
	$matches = curl_exec($cURL);
	curl_close($cURL);
	return $matches;
}

/** Autocomplete handler for the form
 * @param $string string 
 * 	String to search for
 * @return array 
 * 	Returns an array of the objects that match from BGG API
*/

function _boardgames_autocomplete($string) {
	$matches = array();
	$matches = searchBGGbytext($string);

	#if no results are found, return an empty array
	if (empty($matches)) {
		return array();
	}
	else {
		return $matches;
	}
	return $matches;
}
